### ISSUE TITLE
Fails under Node.js v0.8

### ISSUE THREAD

**Issue by SonicHedgehog** [iarna/are-we-there-yet#1]
[The tests fail under Node.js v0.8](https://travis-ci.org/SonicHedgehog/are-we-there-yet/jobs/54465485):

```
util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/home/travis/build/SonicHedgehog/are-we-there-yet/index.js:115:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/travis/build/SonicHedgehog/are-we-there-yet/test/tracker.js:3:15)
    at Module._compile (module.js:449:26)
not ok test/tracker.js .................................. 0/1
    Command: "/home/travis/.nvm/v0.8.28/bin/node tracker.js"
    TAP version 13
    not ok 1 test/tracker.js
```

**Comment by kgryte** [comment]
+1. Getting the same error.

**Comment by kgryte** [comment]
Despite the fix being merged into this module, I am still getting build errors. From what I can tell, `npmlog` allows patches to `are-we-there-yet`, so `1.0.4` should be fine. Any ideas where the problem still lies? cc @SonicHedgehog

**Comment by SonicHedgehog** [comment]
npmlog does indeed specify are-we-there-yet as `~1.0.0`, however, npm itself bundles npmlog (and its dependencies). I have already [opened a pull request](https://github.com/npm/npm/pull/7820) there to resolve this.

**Comment by kgryte** [comment]
Awesome. Thanks.

**Comment by SonicHedgehog** [comment]
[The tests now pass under Node.js v0.8](https://travis-ci.org/SonicHedgehog/are-we-there-yet/jobs/56922271).

**Comment by kgryte** [comment]
@SonicHedgehog Still getting a failed build for the same reason. Are we still waiting for the NPM patch to land?

**Comment by SonicHedgehog** [comment]
@kgryte While the pull request has been merged, no new version of npm has been released, yet. Additionally, some [other things seem to be failing under Node.js v0.8](https://github.com/npm/npm/issues/7842).

**Comment by SonicHedgehog** [comment]
@kgryte Actually, that’s no longer true. npm v2.7.6 has been released as a pre-release and [it will fix the issues](https://travis-ci.org/SonicHedgehog/are-we-there-yet/jobs/57076282) that I have encountered.
