### ISSUE TITLE
trackerStream.isFinish() ?

### ISSUE THREAD

**Issue by demurgos** [iarna/are-we-there-yet#36]
Hi!
I have a question about this part of the documentation:

> # Shared Methods
> -   tracker.finish()
> 
> Marks the tracker as completed. With a TrackerGroup this marks all of its components as completed.
> 
> Marks all of the components of this tracker as finished, which in turn means that tracker.completed() for this will now be 1.
> 
> This will result in one or more change events being emitted.

It states that every tracker does implement `.finish()`. However in the code, `TrackerStream` extends `stream.Transform` and then delegates `complete` and `addWork` to its `tracker` attribute. I do not see any `.finish()` method defined anywhere. Am I missing something ?
I am currently writing a `typings` definition for this module and this causes me some issues.

**Comment by demurgos** [comment]
It's been almost a year, could you confirm or not that the `TrackerStream` has a `.finish` method ?

**Comment by iarna** [comment]
no, it does not, the docs are wrong.
