### ISSUE TITLE
add a license file

### ISSUE THREAD

**Issue by robertkowalski** [iarna/are-we-there-yet#4]
please add a license file :)

**Comment by slang800** [comment]
You can find it in the package.json: https://github.com/iarna/are-we-there-yet/blob/8e711e83c7ceb2daa0183b8a9d81559f444b63ee/package.json#L14

**Comment by robertkowalski** [comment]
thank you for the heads up, but that is not a license *file* which many huge enterprises / their lawyers require

**Comment by robertkowalski** [comment]
@slang800 the problem is that i think all OSS require that you include them full text, here is the relevant snippet from the ISC license:

`Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.`

source: https://opensource.org/licenses/ISC
