### ISSUE TITLE
chore(package): tiny tiny cleanup in packaged contents

### ISSUE THREAD

**Issue by BrainCrumbz** [iarna/are-we-there-yet#93]
Hi there

Just stumbled upon your library in our project `node_modules` directory, not sure which package is using it as a dependency. Used version is 1.1.4.

As a tiny tiny improvement, would you consider removing a couple of not needed (?) files from packaged contents?

Currently: 

```
> dir /b
CHANGES.md
CHANGES.md~
index.js
LICENSE
package.json
README.md
tracker-base.js
tracker-group.js
tracker-stream.js
tracker.js
```

From a quick look, *CHANGES.md~* might be dropped. ~~Not sure about the different *.js files, I haven't checked, they might as well be imported one from the other.~~

**Comment by iarna** [comment]
I added a `prepublish` script in 2.7.0 with 61fa9cf to ensure that I don't accidentally publish my editor cruft again.
